[accepted-image]
.bmp.gif.jpg.jpeg.jpe.tif.tiff.png
[accepted-audio]
.aif.aiff.wav.wma.mp3.mp2.pcm.lpcm.mp1.mpa.flac.aac.m4a.ape.oga.adts.apl.mka.m4p
[accepted-video]
.avi.mpeg.mpg.mpeg2.wmv.dat.vob.ts.mov.mkv.m2ts.vc1.divx.flv.dv.ogv.iso.tts.mpeg4.m4v.mp4v.dvr-ms.wtv
[accepted-multi]
.ogg.mp4.asf.3gp.3g2
[accepted-plist]
.m3u.pls.wpl
[accepted-subtitle]
.srt
[mimetype-image]
.bmp,image/bmp
.gif,image/gif
.jpg,image/jpeg
.jpeg,image/jpeg
.jpe,image/jpeg
.tif,image/tiff
.tiff,image/tiff
.png,image/png
[mimetype-audio]
.aif,audio/aiff
.aiff,audio/aiff
.wav,audio/wav
.wma,audio/x-ms-wma
.mp3,audio/mpeg
.mp2,audio/mpeg
.pcm,audio/L16
.lpcm,audio/L16
.mp1,audio/mpeg
.mpa,audio/mpeg
.flac,audio/x-flac
.aac,audio/3gpp
.m4a,audio/mp4
.ape,audio/octet-stream
.ogg,application/ogg
.oga,audio/ogg
.mp4,audio/mp4
.m4p,audio/m4p
.adts,audio/mpeg
.apl,application/octet-stream
.mka,audio/x-matroska
.3gp,audio/3gpp
.3g2,audio/3gpp2
.asf,audio/x-ms-asf
[mimetype-video]
.mp4,video/mp4
.avi,video/avi
.mpeg,video/mpeg
.mpg,video/mpeg
.mpeg2,video/mpeg2
.wmv,video/x-ms-wmv
.dat,video/mpeg
.vob,video/mpeg
.mov,video/quicktime
.mkv,video/x-matroska
.m2ts,video/mpeg
.vc1,video/vc1
.divx,video/avi
.flv,video/x-flv
.dv,video/x-dv
.ogv,video/ogg
.iso,video/mpeg
.ifo,application/octet-stream
.ts,video/mpeg
.tts,video/vnd.dlna.mpeg-tts
.mpeg4,video/mpeg4
.m4v,video/mp4
.mp4v,video/mp4
.dvr-ms,video/x-ms-dvr
.wtv,video/wtv
.3gp,video/3gpp
.3g2,video/3gpp2
.asf,video/x-ms-asf