/* This work is part of OpenLDAP Software <http://www.openldap.org/>.
 *
 * Copyright 1998-2014 The OpenLDAP Foundation.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted only as authorized by the OpenLDAP
 * Public License.
 *
 * A copy of this license is available in the file LICENSE in the
 * top-level directory of the distribution or, alternatively, at
 * <http://www.OpenLDAP.org/license.html>.
 */
/* This file is automatically generated by configure; please do not edit. */

#include "portable.h"
#include "slap.h"

extern OV_init accesslog_initialize;
extern OV_init auditlog_initialize;
extern OV_init collect_initialize;
extern OV_init constraint_initialize;
extern OV_init dds_initialize;
extern OV_init deref_initialize;
extern OV_init dyngroup_initialize;
extern OV_init dynlist_initialize;
extern OV_init memberof_initialize;
extern OV_init ppolicy_initialize;
extern OV_init pcache_initialize;
extern OV_init refint_initialize;
extern OV_init retcode_initialize;
extern OV_init rwm_initialize;
extern OV_init seqmod_initialize;
extern OV_init sssvlv_initialize;
extern OV_init syncprov_initialize;
extern OV_init translucent_initialize;
extern OV_init unique_initialize;
extern OV_init valsort_initialize;

OverlayInit slap_oinfo[] = {
	{ "accesslog", accesslog_initialize },
	{ "auditlog", auditlog_initialize },
	{ "collect", collect_initialize },
	{ "constraint", constraint_initialize },
	{ "dds", dds_initialize },
	{ "deref", deref_initialize },
	{ "dyngroup", dyngroup_initialize },
	{ "dynlist", dynlist_initialize },
	{ "memberof", memberof_initialize },
	{ "ppolicy", ppolicy_initialize },
	{ "pcache", pcache_initialize },
	{ "refint", refint_initialize },
	{ "retcode", retcode_initialize },
	{ "rwm", rwm_initialize },
	{ "seqmod", seqmod_initialize },
	{ "sssvlv", sssvlv_initialize },
	{ "syncprov", syncprov_initialize },
	{ "translucent", translucent_initialize },
	{ "unique", unique_initialize },
	{ "valsort", valsort_initialize },
	{ NULL, NULL },
};

/* end of generated file */
