#!/bin/bash 

#This wrapper script invokes ImageMagick's convert with five input parameters: $infile -sample $targetgeometry -auto-orient $outfile
#The script is invoked when we require conversion from PNG, BMP, and TIF formatted files to JPG.
#GIF and animated GIF are handled by a separate wrapper script.

# Define the WD media crawler component locations on which Twonky depends, including the INSTALL_DIR.
source /usr/local/twonky/cgi-bin/wdmc-defs.sh

$INSTALL_DIR/bin/convert "$@"

