#!/bin/sh

source /usr/local/modules/files/project_features

kill_proc() {
	retry_cnt=10
	proc_name=$1

	PID=""
	while [ ${retry_cnt} -gt 0 ] ; do
		PID=`pidof ${proc_name}`
		if [ -z "${PID}" ] ; then
			break
		fi
		kill -SIGTERM ${PID}
		retry_cnt=`expr ${retry_cnt} - 1`
		usleep 100000
	done
	if [ -n "${PID}" ] ; then
		kill -SIGKILL ${PID}
	fi
}

start() {
	SMB_LOG="/var/log/samba/log.smbd"
	SMB_ENABLE=`xmldbc -g '/system_mgr/samba/enable'`
	if [ "$SMB_ENABLE" = "0" ]; then
		echo -n $"SAMBA function is disabled."
		echo
	else
		if [ ! -e $SMB_LOG ]; then
			mkdir -p /var/log/samba
			touch $SMB_LOG
		fi
		echo -n $"Starting SMBD services: "
		if [ "$PROJECT_FEATURE_MV_TCP_WORKAROUND" = "1" ]; then
			taskset 2 smbd -D
		else
			smbd -D
		fi
		echo
		echo -n $"Starting NMBD services: "
		nmbd -D
		echo
	fi
}	

stop() {
	echo -n $"Shutting down SMBD services: "
	kill_proc smbd
	echo
	echo -n $"Shutting down NMBD services: "
	kill_proc nmbd
	echo
	# remove pid files
	rm -f /var/run/samba/smbd.pid /var/run/samba/nmbd.pid
}	

restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;

  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
