#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin

DAEMON_BASE_NAME=wdappmgr
DAEMON=/usr/sbin/$DAEMON_BASE_NAME
PIDFILE=/var/run/${DAEMON_BASE_NAME}.pid
CONFIGDIR=/etc/wd

processPID()
{
    echo `pidof $DAEMON_BASE_NAME`
}

test -x $DAEMON || exit 5

case $1 in
    start)
	echo "Starting $DAEMON_BASE_NAME"
        renice 0 -p $$
	pid=$(processPID)
	if [ "$pid" != "" ]; then
	    echo "$DAEMON_BASE_NAME is already running"
	    exit 1
	fi
	LD_LIBRARY_PATH=/opt/wd/lib/boost $DAEMON

        status=$?
	if [ $status = 0 ]; then
	    echo "$DAEMON_BASE_NAME started"
	else
	    echo "$DAEMON_BASE_NAME failed to start"
	fi

	#start up AutoStart apps
	if [ $status = 0 ]; then
	    wdappmgr_auto_start.py --start
	fi
        ;;
    stop)
	echo "Stopping $DAEMON_BASE_NAME"
	pid=$(processPID)
	if [ "$pid" = "" ]; then
	    echo "$DAEMON_BASE_NAME is already stopped"
	    exit 1
	fi
	
	kill $pid
        # Wait a little and remove stale PID file
        sleep 1
	pid=$(processPID)
	if [ "$pid" != "" ]; then
	    echo "$DAEMON_BASE_NAME failed to stop"
	    exit 1
	fi

        if [ -f $PIDFILE ]
	then
            rm -f $PIDFILE
        fi
        ;;
    restart|force-reload)
        $0 stop && sleep 5 && $0 start
        ;;
    try-restart)
        if $0 status >/dev/null; then
            $0 restart
        else
            exit 0
        fi
        ;;
    reload)
	echo "Reloading $DAEMON_BASE_NAME"
	pid=$(processPID)
	if [ "$pid" != "" ]; then
	    kill -HUP $pid
	else
	    echo "$DAEMON_BASE_NAME is not running"
	    exit 1
	fi
	echo "$DAEMON_BASE_NAME reloaded"
	exit 0
        ;;
    status)
	pid=$(processPID)
	if [ "$pid" != "" ]; then
	    echo "$DAEMON_BASE_NAME is running"
	else
	    echo "$DAEMON_BASE_NAME is not running"
	    exit 1
	fi
	exit 0
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|rescan|try-restart|force-reload|status}"
        exit 2
        ;;
esac
