#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin

DAEMON_BASE_NAME=wdtms
DAEMON=/opt/wd/bin/$DAEMON_BASE_NAME
PIDFILE=/var/run/${DAEMON_BASE_NAME}.pid
CONFIGDIR=/etc/wd
ENCLOSURELIB=/opt/wd/lib
BOOSTLIB=${ENCLOSURELIB}/boost
ENCLOSURECONFIG=""

. /etc/system.conf

processPID()
{
    echo `pidof $DAEMON_BASE_NAME`
}

setEnclosureConfig()
{
    local enc_config=""
    if [ "${modelNumber}" = "BNEZ" ]; then
	dmidecode --type=memory |grep "NO DIMM" > /dev/null 2>&1
	if [ $? != 0 ]; then
	    enc_config="_SO_DIMM"
	fi
    fi

    echo "${enc_config}"
}

test -x $DAEMON || exit 5

case $1 in
    start)
	echo "Starting $DAEMON_BASE_NAME"
        renice 0 -p $$
	pid=$(processPID)
	if [ "$pid" != "" ]; then
	    echo "$DAEMON_BASE_NAME is already running"
	    exit 1
	fi

	if [ "${modelNumber}" = "" ]; then
	    LD_LIBRARY_PATH=${ENCLOSURELIB}:${BOOSTLIB} $DAEMON
	else
	    ENCLOSURECONFIG=$(setEnclosureConfig)
	    LD_LIBRARY_PATH=${ENCLOSURELIB}:${BOOSTLIB} $DAEMON -config=${CONFIGDIR}/${modelNumber}${ENCLOSURECONFIG}-thermal.xml
	fi

        status=$?
	if [ $status = 0 ]; then
	    echo "$DAEMON_BASE_NAME started"
	else
	    echo "$DAEMON_BASE_NAME failed to start"
	fi
        ;;
    stop)
	echo "Stopping $DAEMON_BASE_NAME"
	pid=$(processPID)
	if [ "$pid" = "" ]; then
	    echo "$DAEMON_BASE_NAME is already stopped"
	    exit 1
	fi
	
	kill $pid
        # Wait a little and remove stale PID file
        sleep 1
	pid=$(processPID)
	if [ "$pid" != "" ]; then
	    echo "$DAEMON_BASE_NAME failed to stop"
	    exit 1
	fi

        if [ -f $PIDFILE ]
	then
            rm -f $PIDFILE
        fi
        ;;
    restart|force-reload)
        $0 stop && sleep 5 && $0 start
        ;;
    try-restart)
        if $0 status >/dev/null; then
            $0 restart
        else
            exit 0
        fi
        ;;
    reload)
	echo "Reloading $DAEMON_BASE_NAME"
	pid=$(processPID)
	if [ "$pid" != "" ]; then
	    kill -HUP $pid
	else
	    echo "$DAEMON_BASE_NAME is not running"
	    exit 1
	fi
	echo "$DAEMON_BASE_NAME reloaded"
	exit 0
        ;;
    status)
	pid=$(processPID)
	if [ "$pid" != "" ]; then
	    echo "$DAEMON_BASE_NAME is running"
	else
	    echo "$DAEMON_BASE_NAME is not running"
	    exit 1
	fi
	exit 0
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|rescan|try-restart|force-reload|status}"
        exit 2
        ;;
esac
